<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ErrorOr" Version="2.0.1"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bind.Application\Bind.Application.csproj"/>
        <ProjectReference Include="..\Bind.Contracts\Bind.Contracts.csproj"/>
        <ProjectReference Include="..\Bind.Infrastructure\Bind.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
